---
title: Setting up with Blogdown
author: Alex Norman
date: '2017-09-22'
slug: setting-up-with-blogdown
categories:
  - Blogging
summary: An incomplete walkthtrough of my blogdown setup.
tags:
  - blogdown
  - R
  - rmarkdown
math: true
draft: false
output:
  blogdown::html_page:
    toc: true
    number_sections: true
    toc_depth: 1
---

```{r include = FALSE}
knitr::opts_chunk$set(eval = FALSE, collapse = TRUE, comment = NA, tidy = FALSE)
```

When I decided to make the effort to get back into maintaining my website/blog I knew one of the things that would help was better engagement with the building of the site itself. WordPress is excellent for building websites of many kinds, but I felt a sense of only having partial understanding and control which led, I think, to something of a lack of engagement. I also disliked that I had to login to do anything (in reality I didn't) and that everything was a lot more complicated than it needed to be.

While doing some professional procrastination looking into $\rm \LaTeX$ and plain text document production, I came across `bookdown` and then discovered `blogdown`. I knew right away this was what I needed. `R + blog = commitment` (hopefully). Because I found the setup guides I read so helpful, and because I figured creating a recording of my choices may be useful, I decided to write a basic setup post.

{{% alert note %}}
My methods and choices might not suit you. Likewise, my knowledge is incomplete. If you want to set up your own site, make sure you read the appropriate documentation before you begin.
{{% /alert %}}

# Setup
The first thing I did was read the [blogdown book](https://bookdown.org/yihui/blogdown/). The book was written by the author of the package,[Yihui Xie](https://yihui.name/), and two co-authors; [Amber Thomas](https://proquestionasker.github.io/)[^1] and [Alison Presmanes Hill](https://apreshill.rbind.io/). The book is a comprehensive guide to getting started with the `blogdown` package to build a website with [Hugo](https://gohugo.io/). There are some good recommendations 

Easy install package + Hugo is doable within RStudio thank you Blogdown.

My install threw some warnings.

I also really liked Alison Presmanes Hill's 'blue.css' look, so I cloned that and used it here. 

# Google Analytics
Going to Google Analytics I realised I already had a blogspot (two, in fact) being tracked. Took some time to figure out how to get my tracking code. In the end:

* Admin
* Account dropdown menu -> Create new account (you can have up to 100)
* Follow prompts from there. Easy enough. I already had a address to input, so it might be worth leaving this until you know where your site is going to be. 

When I first tried to serve the site I got this error:
```
Error: unknown command "#" for "hugo"
Run 'hugo --help' for usage.
Error: unknown command "#" for "hugo"
Run 'hugo --help' for usage.
The system cannot find the path specified.
Error in shell(cmd, mustWork = TRUE, intern = intern) :
  '"C:\Users\Aarle\AppData\Roaming\Hugo\hugo.exe" -b /"/"  # End your URL with a `/` trailing slash. -D -F -d "public" -t hugo-academic' execution failed with error code 1
In addition: Warning messages:
1: running command '"C:\Users\Aarle\AppData\Roaming\Hugo\hugo.exe" -b /"/"  # End your URL with a `/` trailing slash. -D -F -d "public" -t hugo-academic' had status 65535
2: running command '"C:\Users\Aarle\AppData\Roaming\Hugo\hugo.exe" -b /"/"  # End your URL with a `/` trailing slash. -D -F -d "public" -t hugo-academic' had status 65535
3: running command 'C:\WINDOWS\system32\cmd.exe /c "C:\Users\Aarle\AppData\Roaming\Hugo\hugo.exe" -b /"/"  # End your URL with a `/` trailing slash. -D -F -d "public" -t hugo-academic' had status 1
```
But within 5mins of searching for possible causes of this error, I found that simply pasting this code into the .toml file stopped it. 
```
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
```

Whether it's the right thing to do is another matter.

# Searching for Ideas
Later on, while hunting around for tips and ideas I came across this site, by Yu Cheng https://fischcheng.github.io/2017/02/27/updated-hugo-academic-theme-to-sync-the-upstream-repo/
which demonstrates shortcodes for Twitter, Instagram, and YouTube content. Awesome!
Of course, that led me down a rabbithole, which yielded the Hugo platform's [own page about shortcodes](https://gohugo.io/content-management/shortcodes/).

[^1]: 
Amber's site has some great examples of dataviz using `R`.